# 1. 清理FLUXNET tier2 hourly数据
> Dongdong Kong, CUG, 2024-03-09

```{r}
library(Ipaper)
library(dplyr)

fs <- dir("Z:/DATA/FLUXNET/FLUXNET2015_Tier2/", "FULLSET_HH|FULLSET_HR", 
  recursive = TRUE, full.names = TRUE)
f = fs[1]
```

```{r}
lst = foreach(f = fs, i = icount()) %do% {
  runningId(i)
  fout = basename(f) %>% paste0("./OUTPUT/FLUXNET212_hour_tier2/", "tidied_", .)

  if (!file.exists(fout)) {
    d = fread(f)   
    tryCatch({
      r = tidy_hourly_fullset(d)
      fwrite(r, fout)    
    }, error = function(e) {
      message('%s', e$message)
    })
  }
}
# 8个变量存在`_F_MDS`
```

## 1.1. 把所有文件的数据合并到一起

```{r}
indir = "./OUTPUT/FLUXNET212_hour_tier2/"
fs = dir2("./OUTPUT/FLUXNET212_hour_tier2/")
sites = str_extract(basename(fs), "(?<=FLX_).*(?=_FLUXNET)")
names(fs) = sites

lst = fread_dir(indir, list2df = FALSE)

vars = map(lst, names) |> unlist() |> table()
vars_may <- c(paste0("SWC_F_MDS_", 1:7), paste0("TS_F_MDS_", 1:9))

for (i in 1:length(lst)) {
  runningId(i)

  d = lst[[i]]
  for (var in vars_may) {
    if (var %!in% names(d)) {
      d[[var]] = NA_real_
    }
  }
  # lst[[i]] = d |> relocate(starts_with(c("SWC_F_MDS_", "TS_F_MDS_")), .after = "G_F_MDS")
  lst[[i]] = d |> select(all_of(vars))
}

# > 注意，时间被加了8个小时, 需要注意
df = melt_list(lst, site = sites)
df2 = df |> mutate(
  site = gsub("_", "", site), 
  date = date + dhours(8))
fwrite(df2, "tidied_FLUXNET212_hour_tier2_v20240309.csv")
tidyfst::export_fst(df, "tidied_FLUXNET212_hour_tier2_v20240309.fst")
```

## 1.2. 变量的单位

- `Radiation`: `W m-2` 
- `PPFD_IN`, `CO2_F_MDS`: `µmolPhoton m-2 s-1`
- `Temperature`: `°C`
- `SWC_F_MDS`: `%`
- `Carbon`: has been convert `umolC/m2/s` to `gC/m2/d`
- `VPD`: kPa

> 变量优先采用的是：`consolidated from OBS and OBS_ERA`

## 1.3. 然后挑选变量年，为BEPS模型做准备
